FROM python:3.8 AS BASE
LABEL maintainer="sachajw@gmail.com"

COPY . /app

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.8

RUN pytest -q --flake8
RUN pytest --cov=./ --cov-report=html

ENV MAX_SIZE=10000

EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["app/bubble-sort.py"]
